### ISSUE TITLE
[FEAT] Implement Backend API for Blog Post Deletion

### ISSUE THREAD

**Issue by Ukeme-Edet** [hngprojects/hng_boilerplate_python_fastapi_web#23]
### Description
Create a RESTful API endpoint to handle the deletion of blog posts. This endpoint will allow authorized users to remove their blog posts from the system, with appropriate checks for permissions and post existence.

### Acceptance Criteria
API Endpoint Implementation:
* The endpoint should be accessible at `/api/posts/{postId}`.
* The endpoint should accept HTTP DELETE requests.

Data Validation and Authorization:
* Validate that the user making the request has the necessary permissions to delete the specified post.
* Verify the post's existence with the given ID in the database.

Deleting the Blog Post:
* Upon successful validation, remove the blog post from the database.
* Implement soft delete functionality for potential future recovery of deleted posts.

Response:
* On success, return a 200 OK status code with a success message.
* On failure, return appropriate error codes with descriptive messages.

#### Request Example:
DELETE `/api/posts/123`

Successful Response:
```json
{
  "message": "Blog post successfully deleted",
  "status": 200
}
```
Error Response:
```json
{
  "message": "Unable to delete blog post",
  "errors": [
    "User not authorized to delete this post"
  ],
  "status_code": 404
}
```

#### Purpose
Provide a secure and efficient backend service for blog post deletion, ensuring proper authorization and data integrity.

#### Requirements

- [ ] Develop server-side logic to handle blog post deletion requests.
- [ ] Implement authorization checks to ensure users can only delete their posts.
- [ ] Create database queries for soft deletion of blog posts.
- [ ] Design and implement error handling for various scenarios.

#### Expected Outcome
A fully functional API endpoint that securely handles blog post deletion requests, maintaining data integrity and user permissions.

#### Status Codes
- 200: Blog post was successfully deleted (soft delete).
- 403: User not authorized to delete the specified post.
- 500: A server error occurred.

#### Testing
- [ ] Write unit tests to verify the correct handling of authorized and unauthorized deletion attempts.
- [ ] Test that requests for non-existent posts return a success response.
- [ ] Verify the successful removal of posts from the database.

**Comment by codeReaper0** [comment]
This issues has been taking and it has been approved

**Comment by Ukeme-Edet** [comment]
Okay 🥲
