### ISSUE TITLE
Database Schema - Modeling, Migrations and Seeding

### ISSUE THREAD

**Issue by Armolas** [hngprojects/hng_boilerplate_python_fastapi_web#44]
## Description

Set up the database for this project using  SQLAlchemy, and PostgreSQL as the selected DB, which would also be configurable to accommodate other DB flavors. Additionally, it will ensure a secure database design for users, profile and organizations tables. This setup would follow the migrations, models, and service patterns that are commonly used in projects such as this.

### Acceptance Criteria
To validate the setup,  it would complete the following steps:

**Tables and Constraints**
- [ ] Create users, profiles, organizations, product tables
- [ ] A user has one profile
- [ ] A user have a single profile
- [ ] A user belongs to many organizations
- [ ] An organization has many users

**Tables seeding**
- [ ] At least 2 users
- [ ] At least 3 organizations
- [ ] User one belongs to 2 of the organizations
- [ ] User 2 belongs to all 3 organizations

### Expected outcome

A well-structured database including the necessary migrations and models, with appropriate relationships such as one-to-one and one-to-many, along with seeders to populate the database with dummy data.

**Comment by Dev-wonderful** [comment]
Add the preferred ORM for this project, `Set up the database for this project using SQLAlchemy`

Use your words to say what you would be doing

**Comment by Armolas** [comment]
The words have been updated sir

**Comment by SundayMba** [comment]
task already implemented by the team lead.
