### ISSUE TITLE
[FEAT]: Update a user's role

### ISSUE THREAD

**Issue by willgee9531** [hngprojects/hng_boilerplate_python_fastapi_web#510]
## Description
Implement a PUT endpoint to update a user's role as a superadmin.

## Authentication and Authorization
* API endpoint requires a valid JWT token in the Authorization header
* Only users with superadmin privileges can access this endpoint

## Acceptance Criteria
- Implement PUT endpoint: `/api/v1/superadmin/roles/{user_id}`
- Allow superadmin to update the role of a specified user
- Implement proper authentication and authorization checks

## Data Validation and Sanitization:
- Validate that the `user_id` is a valid UUID
- Ensure the JWT in the Authorization header is valid and not expired
- Verify that the requesting user has superadmin privileges

## Purpose
- To provide a way for superadmins to modify user roles within the system

## Expected Outcome
- A fully functional endpoint that updates a user's role, with proper authentication and authorization checks in place.

### 1. Update User Role [PUT] /api/v1/superadmin/roles/{user_id}

**Request Headers:**
>Authorization: Bearer <JWT_TOKEN>

**Request Body:**
```json
{
  "role": "admin"
}
```
**Success Response (200 OK):**
> Content-Type: application/json
```json
{
  "status": "200",
  "message": "User role updated successfully",
  "data": {
    "user_id": "u1i2d3-4567-89ab-cdef-0123456789ab",
    "email": "user@example.com",
    "name": "John Doe",
    "role": "admin"
  }
}
```
**Failure Response (404 Not Found):**
> Content-Type: application/json
```json
{
  "error": "Not Found",
  "message": "User not found"
}
```
## Error Handling
* Invalid user_id (not a UUID): Return 400 Bad Request with appropriate error message
* User not found: Return 404 Not Found with appropriate error message
* Unauthorized access: Return 403 Forbidden with appropriate error message
* Invalid or expired JWT: Return 401 Unauthorized with appropriate error message
* Server errors: Return 500 Internal Server Error with a generic error message

## Requirements
 - [ ] Implement PUT endpoint for updating user roles
 - [ ] Implement JWT authentication protection for the API endpoint
 - [ ] Implement authorization checks for superadmin access
 - [ ] Write unit tests for the endpoint

## Testing
* Unit tests for the PUT endpoint
* Test cases for authentication and authorization
* Test cases for error scenarios (invalid UUID, user not found, etc.)

**Comment by joboy-dev** [comment]
Not relevant
